export const countryOptions = [
  { label: "Nepal", value: "NP" },
  { label: "India", value: "IN" },
  { label: "United States", value: "US" },
  { label: "United Kingdom", value: "GB" },
  { label: "Canada", value: "CA" },
  { label: "Australia", value: "AU" },
  { label: "Germany", value: "DE" },
  { label: "France", value: "FR" },
  { label: "Japan", value: "JP" },
  { label: "China", value: "CN" },
  { label: "South Korea", value: "KR" },
  { label: "Sri Lanka", value: "LK" },
  { label: "Bangladesh", value: "BD" },
  { label: "Pakistan", value: "PK" },
  { label: "Bhutan", value: "BT" },
  { label: "Maldives", value: "MV" },
  { label: "Singapore", value: "SG" },
  { label: "Malaysia", value: "MY" },
  { label: "Thailand", value: "TH" },
  { label: "United Arab Emirates", value: "AE" },
  { label: "Saudi Arabia", value: "SA" },
  { label: "Qatar", value: "QA" },
  { label: "Kuwait", value: "KW" },
  { label: "Philippines", value: "PH" },
  { label: "Vietnam", value: "VN" },
];
