export const countries = [
  { label: "Abu Dhabi", value: "Abu Dhabi" },
  { label: "Ajman", value: "Ajman" },
  { label: "Australia", value: "Australia" },
  { label: "Austria", value: "Austria" },
  { label: "Belgium", value: "Belgium" },
  { label: "Canada", value: "Canada" },
  { label: "China", value: "China" },
  { label: "Croatia", value: "Croatia" },
  { label: "Cyprus", value: "Cyprus" },
  { label: "Denmark", value: "Denmark" },
  { label: "Dubai", value: "Dubai" },
  { label: "Finland", value: "Finland" },
  { label: "France", value: "France" },
  { label: "Georgia", value: "Georgia" },
  { label: "Germany", value: "Germany" },
  { label: "Greece", value: "Greece" },
  { label: "Hungary", value: "Hungary" },
  { label: "Indonesia", value: "Indonesia" },
  { label: "Ireland", value: "Ireland" },
  { label: "Italy", value: "Italy" },
  { label: "Japan", value: "Japan" },
  { label: "Kazakhstan", value: "Kazakhstan" },
  { label: "Latvia", value: "Latvia" },
  { label: "Lithuania", value: "Lithuania" },
  { label: "Luxembourg", value: "Luxembourg" },
  { label: "Malaysia", value: "Malaysia" },
  { label: "Malta", value: "Malta" },
  { label: "Mauritius", value: "Mauritius" },
  { label: "Monaco", value: "Monaco" },
  { label: "Netherlands", value: "Netherlands" },
  { label: "New Zealand", value: "New Zealand" },
  { label: "Poland", value: "Poland" },
  { label: "Ras Al Khaimah", value: "Ras Al Khaimah" },
  { label: "Russia", value: "Russia" },
  { label: "Saudi Arabia", value: "Saudi Arabia" },
  { label: "Sharjah", value: "Sharjah" },
  { label: "Singapore", value: "Singapore" },
  { label: "South Korea", value: "South Korea" },
  { label: "Spain", value: "Spain" },
  { label: "Sri Lanka", value: "Sri Lanka" },
  { label: "Sweden", value: "Sweden" },
  { label: "Switzerland", value: "Switzerland" },
  { label: "Thailand", value: "Thailand" },
  { label: "Umm Al Quwain", value: "Umm Al Quwain" },
  { label: "UK", value: "UK" },
  { label: "USA", value: "USA" },
  { label: "Vietnam", value: "Vietnam" },
];
