const course = [
  "B.S.B.A. in Business Administration",
  "B.S. in Economics",
  "B.S. in Engineering",
  "B.S. in Civil Engineering",
  "B.S. in Electrical Engineering",
  "B.S. in Mechanical Engineering",
  "B.S. in Engineering Management",
  "B.S. in Computer Science",
  "B.S. in Data Science",
  "B.S. in Public Health Sciences",
  "B.S. in Exercise Science",
  "B.S. in Anthropology",
  "MSc Biomedical Science",
  "MSc Data Science and Business Analytics",
  "MSc Business and Management",
  "MSc Applied Marine Science",
  "MA Architectural Design",
  "MSc Civil Engineering",
  "MSc Marine Conservation",
  "MSc Psychology",
  "MSc Artificial Intelligence",
  "MSc Electrical and Electronic Engineering",
  "MA Fine Art",
  "MA Experience Design",
  "(MBA) Master of Business Administration",
  "MSc Project Management",
  "BSc (Hons) Biological Sciences",
  "BSc (Hons)  Nursing (Mental Health)",
  "BSc (Hons) Psychology",
  "Sc (Hons) Computer Science",
  "MEng (Hons) Robotics",
  "BA (hons) Fine Art",
  "BSc (Hons) Marine Biology",
  "Meng (Hons) Civil Engineering",
  "BA (Hons) Architecture",
  "BSc (Hons) Economics",
  "BEng (Hons) Electrical and Electronic Engineering",
  "BSc (Hons) Physiotherapy",
  "BSc (Hons) Business Management",
  "BA (Hons) Architecture (University Foundation)",
  "BSc (Hons) Biomedical Science (University Foundation)",
  "BSc (Hons) Computer Science (University Foundation)",
  "BEng (Hons) Civil Engineering (University Foundation)",
  "BEng (Hons) Electrical and Electronic Engineering (University Foundation)",
  "BSc (Hons) Nursing (Adult Health) (University Foundation)",
  "LLB (Hons) Law (University Foundation)",
  "MSc Business and Management (Pre-Masters)",
  "MSc Finance (Pre-Masters)",
  "MSc International Business (Pre-Masters)",
  "MSc International logistics and Supply chain management (Pre-Masters)",
  "M.S. in Business Analytics",
  "M.S. in Computer Science",
  "M.S. in Data Science",
  "M.S. in Electrical Engineering",
  "M.S. in Materials Science and Engineering",
  "M.S. in Finance",
  "M.S. in Engineering Management",
  "M.S. in Artificial Intelligence",
  "M.S. in Kinesiology",
  "B.S. in Construction Management",
  "B.S. in Cybersecurity",
  "B.S. in Construction Engineering Technology",
  "B.S. in Materials Science and Engineering",
  "B.S. in Kinesiology",
  "B.B.A. in Business Analytics",
  "B.B.A. in Entrepreneurship and Enterprise Management",
  "Master of Professional Accounting",
  "Master of Business Administration",
  "Master of Counselling",
  "Master of Social Work (Qualifying)",
  "Master of Music",
  "Bachelor of Management and Entrepreneurship",
  "Bachelor of Business (Accounting)",
  "Bachelor of Dramatic Art",
  "Bachelor of Music",
  "Bachelor of Screen Production",
  "Bachelor of Early Childhood Education (Birth to 5)",
  "Master of Design (Innovation)",
  "Master in Computer Science",
  "Master of Science in Hospitality And Tourism",
  "Master of Arts (Social Science)",
  "Master of Arts (Communication Management)",
  "Master of Business Administration- Enterprise Risk Management",
  "Master of Business Administration- Marketing Leadership",
  "Bachelor of Business (Hons)",
  "Bachelor of Accountancy (Hons)",
  "Bachelor of Arts (Hons) in Interior Architecture",
  "Bachelor of Art (Hons) Digital Media Production",
  "Bachelor of Game Development (Honours)",
  "Bachelor of Mechatronics Engineering with Honours",
  "Bachelor of Culinary Management (Hons)",
  "Bachelor in Software Engineering (Hons)- Internet of Things",
  "MA Design Management",
  "MA Luxury Brand Management",
  "MSc Business and Data Analytics",
  "MSc Accounting and Finance",
  "MSc Strategic Marketing and Analytics",
  "MBA (Fashion Business and Entrepreneurship)",
  "MFA Digital Photography",
  "MSc Computer Science",
  "MSc Cyber Security",
  "BA (Hons) 3D Animation",
  "BA (Hons) Advertising and Brand Design",
  "BA (Hons) Animation",
  "BA (Hons) Character Design and Concept Illustration",
  "BA (Hons) Digital Content Creation",
  "BA (Hons) Fashion Buying and Brand Management",
  "BA (Hons) Games Art",
  "BA (Hons) Games Design",
  "BA (Hons) Games Development",
  "BA (Hons) Interior Design",
  "BA (Hons) Urban Landscape Architecture",
  "BSc (Hons) Digital Marketing",
  "B.S. in Accounting",
  "B.S. in Biology",
  "B.S. in Biomedical Engineering",
  "B.S. in Business Administration",
  "B.S. in Chemical Engineering",
  "B.S. in Chemistry",
  "B.S. in Computer Engineering",
  "B.S. in Construction Engineering",
  "B.S. in Design",
  "B.S. in Entrepreneurship",
  "B.S. in Finance",
  "B.S. in Information Systems",
  "B.S. in Marketing",
  "B.S. in Nursing",
  "B.S. in Physics",
  "Master of Science in International Business",
  "Graduate Diploma in Management",
  "Master of Science in Management",
  "Master of Science in Accounting and Financial Management",
  "Graduate Diploma in Business Analytics",
  "Graduate Diploma in Data Science",
  "Graduate Diploma in Machine Learning and Artificial Intelligence",
  "Graduate Diploma in User Experience",
  "Bachelor of Business (Management)",
  "Bachelor of Computer Science (Digital Systems Security and Cyber Security)",
  "Bachelor of Science (Honours) in Finance",
  "Bachelor of Arts (Communication)",
  "Diploma in Banking and Finance",
  "Diploma in Information Technology",
  "Graduate Certificate in Web Development",
  "Graduate Certificate in Applied Artificial Intelligence & Machine Learning (Optional Co-op)",
  "Graduate Certificate in Software Quality Assurance and Test Engineering (Optional Co-op) + Graduate Certificate in Big Data Solutions Architecture (Optional Co-op)",
  "Graduate Certificate in Information Technology Project Management",
  "Graduate Certificate in Financial Technology",
  "Graduate Certificate in Supply Chain Management - Global",
  "Graduate Certificate in Information Technology Business Analysis",
  "Graduate Certificate in Enhanced Practice for Internationally Educated Nurses",
  "Graduate Certificate in Sustainable Urban Design",
  "Graduate Certificate in Therapeutic Recreation",
  "Bachelor of Business Administration (Honours) - International Business Management",
  "Bachelor of Commerce (Honours) - Financial Services",
  "Bachelor of Engineering (Electronics, Mechanical, Building Systems, Power System, Cyber Systems)",
  "Bachelor of Computer Science (Honours) (Co-op)",
  "Advanced Diploma in Computer Engineering Technology (Optional Co-op)",
  "Diploma in Occupational Therapist Assistant & Physiotherapist Assistant",
  "Diploma in Business - Supply Chain and Operations for Commercial Trucking",
  "Diploma in Early Childhood Education",
  "Diploma in Computer Programming",
  "Certificate in Personal Support Worker - International",
  "Graduate Certificate in Academic Foundations",
  "Diploma of Business",
  "Diploma of Communication",
  "Diploma of Design",
  "Diploma of Information Technology",
  "Diploma of Heath",
  "Diploma of Science",
  "Master of Health Management",
  "Graduate Certificate in Health Management",
  "Graduate Diploma in Health Management",
  "Master of Public Health (Extended)",
  "Bachelor of Nursing",
  "Bachelor of Early Childhood Education (Birth to Five)",
  "B.S. in Biological Sciences",
  "Bachelors of Biomedical Engineering",
  "Bachelors of Chemical Engineering",
  "Bachelors of Construction Engineering and Management",
  "B.S. in Fashion Merchandising & Management",
  "B.S. in Management Information Systems (MIS)",
  "B.S. in Business Analytics",
  "Master of Science in Marketing and Analytics",
  "Master of Science in Technology and Entrepreneurship",
  "Master’s in Artificial Intelligence",
  "Master’s in Hospitality Management",
  "Master’s in International Business Management",
  "Bachelor of Business Administration (BBA)",
  "Bachelor's degree in AI & HCI (Artificial Intelligence & Human-Computer Interaction)",
  "Bachelor's degree in Cognitive Science",
  "Bachelor's degree in Culinary Arts",
  "Bachelor's degree in Data Science",
  "Bachelor's degree in Global Hotel Management",
  "Bachelor's degree in Global Management",
  "Bachelor's degree in K-Beauty Design",
  "Bachelor's degree in K-Pop Arts Management",
  "Bachelor's degree in Media and Communication Arts",
  "Bachelor's degree in Restaurant and Entrepreneurship",
  "Bachelors of Engineering in AI and Big Data",
  "Ph.D. in Global Management",
  "Ph.D. in Hospitality and Tourism Management",
  "Ph.D. in Management Studies",
  "M.S. in Biology",
  "M.M. in Music Composition",
  "M.M. in Music Performance",
  "M.M. in Music Education",
  "M.A. in Language and Learning",
  "M.S.Ed. In Math Education",
  "M.S. in Speech-Language Pathology",
  "B.A. in Economics",
  "B.S. in Business Administration - Management",
  "B.S. in CommunicationDigital Film Production",
  "B.S. in Biochemistry",
  "B.S. in Molecular Genetics",
  "B.S. in Medical Laboratory Science",
  "B.S. in Sport Management",
  "B.S. in Computer Information Systems",
  "B.F.A. in Animation and Illustration",
  "B.F.A. in Film & Video Arts",
  "B.F.A. in Graphic Design",
  "B.S. in Environmental Science",
  "B.S. in Mathematics",
  "B.S. in Psychology",
  "MA in Migration, Climate Change and Environment",
  "MA — Management and Leadership",
  "Master of Arts in Counseling",
  "Master of Science in Cybersecurity Operations",
  "MBA — Master of Business Administration",
  "Bachelor of Arts in Economics",
  "Bachelor of Arts in International Relations",
  "Bachelor of Arts in Management",
  "Bachelor of Arts in Media Studies",
  "Bachelor of Arts in Photography",
  "Bachelor of Arts in Psychology",
  "Bachelor of Science in Business Administration",
  "Bachelor of Science in Computer Science",
  "Bachelor of Science in Finance",
  "Bachelor of Science in Psychology",
  "MSc Addiction and Mental Health",
  "Msc Bioinformatics  Genomic Medicine",
  "MSc Business Analytics",
  "Msc Business and Management",
  "Msc Computer Science",
  "Msc Cyber Security",
  "Msc  Engineering Management",
  "MPH Public Health",
  "MSc Supply Chain Management",
  "MBA",
  "BSc (Hons)  Accounting and Finance",
  "BSc (Hons) Artificial Intelligence and Robotics",
  "BEng (Hons) Biomedical Engineering",
  "BSc (Hons) Business Analytics",
  "BSc (Hons) Business Enterprise Development",
  "BSc (Hons) Computer Science",
  "BSc (Hons)  International Business and Management",
  "LLB (Hons)",
  "BSc (Hons)  Neuroscience",
  "MPharm Pharmacy",
  "Master of Finance",
  "Master of Supply Chain Management and Logistics",
  "Bachelor of Commerce (Business Analytics, Finance, Accounting, Humar Resources Management, Logistics & Supply Chain, Marketing)",
  "Bachelor of Science (Computer Science, Mathematics, Agriculture, Food Science)",
  "Bachelor of Health Sciences",
  "Bachelor of Science in Civil Engineering",
  "Bachelor of Science in Computer Engineering",
  "Bachelor of Fine Arts (Honours) in Graphic Design",
  "Bachelor of Science (General)",
  "Bachelor of Science (Honours) in Computer Science (Co-op)",
  "M.S. in Bioengineering",
  "M.S. in Civil Engineering",
  "M.S. in Computer Engineering",
  "Master’s in Industrial Engineering and Operations Research",
  "M.S. in Structural Engineering",
  "Master of Public Health (MPH)",
  "M.S. in Management",
  "Master of Business Administration (MBA)",
  "Master of  Information Technology",
  "Master of  Tourism and Hospitality",
  "Master of  Psychology",
  "Master of  Philosophy",
  "MBA- Analytics and Business Solutions",
  "Bachelor of Business",
  "Bachelor of Commerce",
  "Bachelor of Information Technology",
  "Bachelor of Psychological Science",
  "Bachelor of Tourism, Hospitality, and Events",
  "Bachelor of Education (Early Childhood Education)",
  "Post Degree Diploma in Accounting",
  "Post Degree Diploma in Accounting Studies",
  "Post Degree Diploma in Financial Planning",
  "Post Degree Diploma in Financial Analysis",
  "Post Degree Diploma in Marketing",
  "Post Degree Diploma in Supply Chain Management",
  "Post-Baccalaureate Diploma in Accounting",
  "Post-Baccalaureate Diploma in Finance",
  "Post-Baccalaureate Diploma in International Supply Chain Management",
  "Post-Baccalaureate Diploma in Digital Marketing",
  "Bachelor of Business Administration in Financial Services",
  "Diploma in Geological Resources",
  "Diploma in Sport Science",

  "Diploma in Accounting",
  "Diploma in Computing Studies and Information Systems",
  "Diploma in Criminology",
  "Diploma in Financial Service",
  "Diploma in Legal Studies",
  "Diploma in Marketing",
  "Certificate in Computing Science",
  "M.S. in Aerospace Engineering",
  "M.S. in Biochemistry",
  "M.S. in Biotechnology",
  "M.S. in Flight Test Engineering",
  "M.S. in Mechanical Engineering",
  "B.A. in Psychology",
  "B.S. in Aerospace Engineering",
  "Computer Science MSc",
  "MSc Data Science",
  "MSc Advanced Machine Learning",
  "MSc Drug Discovery",
  "MSc Finance",
  "MSc Management",
  "MSc Automotive Engineering with Business Management",
  "BSc Economics",
  "BSc Psychology",
  "Mechanical Engineering BEng (Hons)",
  "Aerospace Engineering BEng (Hons)",
  "Physics with Astrophysics BSc (Hons)",
  "Mathematics, Statistics and Data Science BSc (Hons)",
  "Computer Science and Artificial Intelligence BSc (Hons)",
  "Sport and Exercise Science BSc (Hons)",
  "Sport Management and Coaching BSc (Hons) with Professional Placement",
  "Management BSc (Hons) with Work Placement",
  "Higher Diploma in Science in Computing",
  "MSc in Artificial Intelligence",
  "MSc in Cloud Computing",
  "MSc in Cyber Security",
  "MSc in Data Analytics",
  "MSc in Business Analytics for Decision Makers",
  "MSc in Finance",
  "MSc in Management",
  "MSc in Marketing",
  "MSc in International Business",
  "MSc in Accounting",
  "BA (Honours) in Early Childhood Education and Care",
  "BSc (Honours) in Data Science",
  "BA (Honours) in Accounting and Finance",
  "BA (Honours) in Business",
  "BA (Honours) in Human Resource Management",
  "BA (Honours) in Marketing Practice",
  "BA (Hons) in Psychology",
  "BSc (Honours) in Computing",
  "Executive MBA",
  "Flex MBA",
  "Global MBA",
  "Master of Science (MSc) in Global Business",
  "MBA in Sports Management",
  "Swiss French Dual Degree Blended MBA",
  "Bachelor of Science (BSc) in Business Administration",
  "Bachelor of Science (BSc) in Business Administration - Business IT",
  "Bachelor of Science (BSc) in Business Administration - Creative Business Management",
  "Bachelor of Science (BSc) in Business Administration - International Business",
  "Msc Accounting and Finance",
  "Msc Advanced Chemical Engineering",
  "MSC Biotechnology",
  "Msc Business Analytics",
  "Msc Business Management",
  "LLM",
  "MSc Work and Organisational Psychology",
  "MSc Computer Science (Artificial Intelligence)",
  "BSc Biochemistry",
  "BSc Health Promotion and Public Health",
  "Beng Chemical Enginnering",
  "BSc Computer Science",
  "Beng Electronics Engg",
  "BA LLB",
  "Bsc International Management",
  "BSc Nursing (Adult)",
  "BSc Physiotherapy",
  "MSc International Business",
  "MSc International Finance",
  "MSc Advanced Computer Science",
  "MSc Cybersecurity (Conversion)",
  "MSc Data Science (Conversion)",
  "MSc Digital Marketing",
  "MSc International Tourism and Hospitality Management",
  "MSc Diabetes",
  "MA Education",
  "MA Art Therapy",
  "MA Education and Leadership",
  "Msc in Fintech and Business Analysis",
  "Msc Programme and Project Management",
  "BA (Hons) Acting",
  "Computer Science with AI",
  "Cyber Security with AI",
  "BA (Hons) Business Management",
  "BSc (Hons) Biomedical Science",
  "BA (Hons) Criminology",
  "BA (Hons) Social Work",
  "BSc (Hons) Forensic Science",
  "BSc (Hons) Nursing Practice",
  "Marine Biology",

  "BA (Hons) Film Production",
  "Bachelor of Commerce ( Business ) - Accounting",
  "Bachelor of Engineering - Aerospace Engineering",
  "Bachelor of Computer Science - Algorithms",
  "Bachelor of Architectural Studies",
  "Bachelor of Commerce ( Business )",
  "Bachelor of Computer Science - Computer Game Development",
  "Bachelor of Computer Science",
  "Bachelor of Arts - Criminology and Criminal Justice",
  "Bachelor of Economics",
  "Bachelor of Science - Food Science",
  "MSc in International Marketing",
  "MSc Operations, Logistics and Supply Chain Management",
  "MSc Cloud Computing",
  "MSc Advanced Architectural Design",
  "MSc Advanced Landscape Planning and Management",
  "MSc Bioinformatics",
  "BSc Honours Biology",
  "BA Honours Business Management",
  "BEng Honours Chemical Engineering",
  "BEng Honours Civil Engineering",
  "BSc Honours Computer Science",
  "BA Honours Education",
  "BSc Honours Environmental Science",
  "BA Honours Journalism, Media and Culture",
  "BEng Honours Mechanical Engineering",
  "BA Honours Politics and Economics",
  "MSc Computer Science - Augmented and Virtual Reality",
  "MSc Computer Science - Data Science",
  "MSc Computer Science - Future Networked Systems",
  "MSc Computer Science - Intelligent Systems",
  "Master in Business Admisitration",
  "MSc in Operations and Supply Chain Management",
  "MSc in Business Analytics",
  "MSc Neuroscience",
  "MSc Financial Risk Management",
  "BA Management science and information systems studies (MSISS)",
  "BA Computer Science",
  "BBS Global Business (Bachelor in Business Studies)",
  "BA Computer science Linguistics and language",
  "BA History of art and architecture",
  "BA BotanyBiological and Biomedical Sciences",
  "BA Environmental SciencesBiological and Biomedical Sciences",
  "BA Molecular MedicineBiological and Biomedical Sciences",
  "BA Physics and AstrophysicsPhysical Sciences",
  "Master of Science in Finance",
  "Master of Business Administration (MBA) - Strategic Marketing",
  "Master of Business Administration (MBA) - Strategic Management",
  "Master of Business Administration (MBA) - Healthcare Administration",
  "Master of Business Administration (MBA) - Global Business and Supply Chain Management",
  "Master of Business Administration (MBA) - Finance",
  "Master of Business Administration (MBA) - Accounting",
  "Master of Science in Information Security and Digital Forensics (ISDF )",
  "Master of Arts(MA) in Disaster/Emergency Management and National Security",
  "Master of Arts(MA) in Criminal Justice Administration",
  "Masters of Business Administration (MBA)- Cyber-security",
  "Masters of Business Administration (MBA)- Finance",
  "Masters of Business Administration (MBA)- Marketing",
  "M.S. in Chemical Engineering",
  "Masters of Computer Science",
  "M.S. in Engineering Mechanics",
  "Masters of Business Administration (MBA)- Business Analytics",
  "M.S. in Materials Engineering",
  "Master of Business Analytics (MBAN)",
  "Master of Finance (MFin)",
  "M.S. in Systems Engineering",
  "B.S.B.A. in Business Economics",
  "Bachelors of Civil Engineering",
  "Bachelors of Electrical Engineering",
  "B.S. in Electronic and Computer Engineering Technology",
  "B.S.B.A. in Entrepreneurship",
  "B.S.B.A. in Finance",
  "B.S. in Industrial Engineering Technology",
  "B.S.B.A. in Marketing",
  "Bachelors of Mechanical Engineering",
  "B.S. in Mechanical Engineering Technology",
  "B.S. in Medicinal-Pharmaceutical Chemistry",
  "B.S.B.A. in Operations and Supply Management",
  "B.S.B.A. in Management",
  "B.S.B.A. in Business Analytics",
  "MSc Advanced Computer Science with Artificial Intelligence",
  "MSc Supply Chain & Logistics Management",
  "MSc Project Management & Innovation",
  "MSc International Management",
  "MSc Investment & Finance",
  "MSc Marketing",
  "MSc Business Analysis & Consulting",
  "MSc Clinical Health Psychology",
  "MSc Counselling & Psychotherapy",
  "MSc Advanced Mechanical Engineering with Energy Systems",
  "MSc Advanced Pharmacology",
  "MSc Advanced Biochemistry",
  "MSc Advanced Construction Technologies & BIM",
  "BA Hons English & Journalism, Media and Communication",
  "LLB Law",
  "BA (Hons) Accounting & Business Analysis & Technology (with Work Placement)",
  "BA (Hons) Finance",
  "BSc (Hons) Immunology & Microbiology",
  "BSc (Hons) Software Engineering",
  "Beng (Hons) Aero-Mechanical Engineering",

  "BBA (Hons) Business Administration",
  "BSc (Hons) Computer Science (with Work Placement)",
  "BEng (Hons) Mechanical Engineering",
  ".Beng (Hons) Civil Engineering (with Work Placement)",
  "M.S. in Digital Marketing",
  "M.S. in Finance & Investment Management",
  "Master of Business Administration (MBA) - General",
  "M.S. in Computer Science & Information Technology",
  "M.S. in Cybersecurity",
  "M.S. in Healthcare Informatics",
  "M.S. in Exercise & Sport Science",
  "M.S. in Chemistry",
  "B.S. in Molecular & Cellular Biology",
  "B.S. in Game Design & Development",
  "B.S. in Information Technology",
  "LLM International Commercial Law",
  "MSc International Business Management",
  "MSc Management and Finance",
  "MBA Master of Business Administration",
  "MSc Engineering Management",
  "MSc Behaviour Change",
  "MSc Environmental Change, Impact and Adaptation",
  "BSc Accounting and Finance",
  "BSc Agriculture",
  "BSc Artificial Intelligence and Robotics",
  "BSc Astrophysics",
  "BSc Business Economics",
  "LLB Business Law",
  "BSc Business and Management",
  "BA Film-making",
  "BA Film and Television / Drama and Theatre",
  "BSc Genetics and Biochemistry",
  "Master of Engineering in Internetworking",
  "Master of Applied Computer Science (MACS)",
  "Master of Digital Innovation (MDI)",
  "Master of Engineering (MEng) - Biological Engineering",
  "Master of Engineering (MEng) - Chemical Engineering",
  "Master of Engineering (MEng) - Industrial Engineering",
  "Master of Public Administration (MPA)",
  "Master of Resource & Environmental Management (MREM)",
  "Master of Information (MI)",
  "Master of Health Administration (MHA)",
  "Master of Marine Management (MMM)",
  "Master of Arts in Economics",
  "Master of Development Economics (MDE)",
  "Master of Planning (MPlan)",
  "MBA - Corporate Residency Pathway",
  "Bachelor of Science in Agriculture - Agricultural Business",
  "Bachelor of Science in Agriculture - Environmental Sciences",
  "Bachelor of Arts in Creative Writing",
  "Bachelor of Computer Science (Co-op)",
  "Bachelor of Computer Science - Artificial Intelligence and Intelligent Systems (Co-op)",
  "Bachelor of Engineering (Co-op)",
  "Bachelor of Engineering - Civil Engineering (Co-op)",
  "Bachelor of Commerce (Co-op)",
  "Bachelor of Science in Statistics (Co-op)",
  "Bachelor of Commerce - Supply Chain and Logistics Management (Co-op)",
  "Graduate Certificate in Internet of Things and Machine Intelligence",
  "Graduate Certificate in Cloud Security",
  "Graduate Certificate in Healthcare Administration and Service Management",
  "Garduate Certificate in Supply Chain Management - Logistics Automation",
  "Graduate Certificate in Artificial Intelligence Development and Applications",
  "Graduate Certificate in Project Management - Information Technology",
  "Graduate Certificate in Mobile Application Development",
  "Graduate Certificate in Clinical Kinesiology (Co-Op)",
  "Graduate Certificate in Urban Design ( Co-Op )",
  "Graduate Certificate in Interactive Media Management",
  "Honours Bachelor of Computer Science (Specializations - Cloud Computing, Data Analytics, Game Engineering, Data Engineering, Network Engineering, Mobile Computing)",
  "Honours Bachelor of Engineering (Specializations - Mechanical Engineering, Electrical Engineering)",
  "Honours Bachelor of Information Sciences (Cyber Security)",
  "Honours Bachelor of Science – Nursing",
  "Honours Bachelor of Animation",
  "Advanced Diploma in Computer Engineering Technology",
  "Diploma in Pharmacy Technician",
  "Diploma in Practical Nursing",
  "Certificate in Personal Support Worker",
  "Master of Science in Health Sciences",
  "Master of Science in Psychology",
  "Master of Science in Business Administration",
  "Master of Engineering in Integrated Wood Design",
  "Master of Arts in Natural Resources and Environmental Studies",
  "Master of Arts in International Studies",
  "Master of Arts in Interdisciplinary Studies",
  "Master of Social Work",
  "Master of Arts in Political Science",
  "Bachelor of Commerce in Accounting",
  "Bachelor of Commerce in International Business",
  "Bachelor of Health Science in Biomedical Studies",
  "Bachelor of Science in Biochemistry and Molecular Biology",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Mathematics and Statistics",
  "Bachelor of Commerce in Management Information System",
  "Bachelor of Applied Science in Civil Engineering",
  "Master of Business Administration with Advanced Studies in Management",
  "Master of Public Health",
  "Master of Science in Computer Science",
  "Master of Education",
  "Master of Arts in History (MA)",
  "Master of Science in Kinesiology (MSc)",
  "Master of Arts in Clinical Psychology (MA)",

  "Master of Science in Physics (MSc)",
  "Master of Science in Civil Engineering",
  "Honours Bachelor of Arts and Science - Media, Film and Communications",
  "Bachelor of Arts-Psychology",
  "Bachelor of Administration",
  "Honours Bachelor of Commerce -Major in Business Administration",
  "Honours Bachelor of Commerce - Major in Marketing",
  "Honours Bachelor of Social Work",
  "Bachelor of Science - Natural Science",
  "Bachelor of Science - Nursing",
  "Honours Bachelor of Science-Forestry",
  "Honours Bachelor of Fine Art - Visual Arts",
  "Master in AI and Automation",
  "Master in Computer Science - Software Engineering",
  "Master in Cybersecurity",
  "Master in Electromechanical Vehicle Engineering",
  "Master in IT and Management",
  "Master in Manufacturing Engineering",
  "Master in Operations and Supply Chain Management",
  "Master in Robotics and Automation",
  "Bachelor in International Mechanical Engineering",
  "BA International Programme in Politics and Economics",
  "MSc Financial Technology",
  "MSc Project management",
  "MSc Psychology (Conversion)",
  "LLM Law",
  "MA International Business",
  "MBA Business Administration (MBA)",
  "MSc Construction Management",
  "MSc Data Science and Artificial Intelligence",
  "BA (Hons) Digital Marketing",
  "BSc (Hons) Construction Management",
  "BSc (Hons) Nursing (Adult)",
  "BA (Hons) Accounting and Finance",
  "BA (Hons) Business and Marketing",
  "Master of Advanced studies in European and Asian",
  "Business Management",
];

export const CourseName = course?.map((c) => ({
  value: c,
}));
