export const ErrorMessage = {
  email: "Email is Required",
  permission: "Permission Name is Required",
  action: "Action is Required",
  name: "Name is Required",
  lastName: "Last Name is  Required",
  phone: "Phone Number is Required ",
  lang: "Language is Required",
  firstName: "First Name is Required",
  password: "Password is Required",
  role: "Role is Required ",
  userType: "User Type is Required",
  universityName: " university is Required",
  course: "Course is Required",
  location: "location is Required",
  position: "working Position is Required",
  Title: "Title is Required",
  Address: "Address is Required ",
  section: " Section is Required",
  countryName: " country Name is Required",
  intake: "in_Take_year is Required",
  gender: "Gender Type is Required",
  studyLevel: "Degree Level is Required ",
  studyCountry: "Where to Study Country Required ",
  dob: "Dob is Required",
  assignee: "Assignee Name is Required",
  counselingMode: "counseling Mode is Required",
  Date: "Date is Required ",
  counselingTime: "counseling Time is Required",
  passOut: "Year of Passing is Required ",
  college_UniversityName: "College/University Name is Required",
  percentageOrGpa: "percentageOrGpa  is Required & dont put any symbloe",
  student: "Student Name is Required",
  description: "description is Required",
  monthlyFee: "Student Monthly Fee is Required",
  RoomType: "Room Type is Required ",
  Payment_Status: "Payment Status is Required",
  amount: "Amount is Required",
  Block: "Hostel Block is Required",
  FatherName: "Father Name is Required",
  nationality: "Nationality is Required",
  PaymentMode: "Payment Mode is Required",

  Empolyee: "Empolyee is Required",
  salary: "salary is Required",

  TotalFee: "University Total Fee is Required",
};
