const countryNameToCode: Record<string, string> = {
  USA: "US",
  UK: "GB",
  Australia: "AU",
  Ireland: "IE",
  Germany: "DE",
  Sweden: "SE",
  Finland: "FI",
  Dubai: "AE",
  AbuDhabi: "AE",
  Singapore: "SG",
  Austria: "AT",
  Malta: "MT",
  Italy: "IT",
  Vietnam: "VN",
  China: "CN",
  Malaysia: "MY",
  Hungary: "HU",
  Lithuania: "LT",
  Spain: "ES",
  Cyprus: "CY",
  NewZealand: "NZ",
  Belgium: "BE",
  SouthKorea: "KR",
  France: "FR",
  Georgia: "GE",
  Monaco: "MC",
  Japan: "JP",
  Ajman: "AE",
  Switzerland: "CH",
  Russia: "RU",
  Croatia: "HR",
  Indonesia: "ID",
  Mauritius: "MU",
  Netherlands: "NL",
  SriLanka: "LK",
  RasAlKhaimah: "AE",
  UAE: "AE",
  SaudiArabia: "SA",
  Canada: "CA",
  Poland: "PL",
  Kazakhstan: "KZ",
};

// Function to get the code
export const getCountryCode = (country: string): string => {
  return countryNameToCode[country] ?? "UN"; // UN = unknown flag
};
